<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Helpdesk-ydrated-686</name>
   <tag></tag>
   <elementGuidId>3fc57352-dbba-47b1-9e06-421859f8ed13</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>nav.w-full > ul > span.collapsed > li > a.primary-link</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Helpdesk')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c55fc46c-0ee2-417c-b9e5-ce9d7bccf347</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>primary-link</value>
      <webElementGuid>737e6005-d096-45f6-940d-256524ae686a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Helpdesk</value>
      <webElementGuid>17ee9169-196b-441c-bca8-a8ba312b74d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/nav[@class=&quot;w-full&quot;]/ul[1]/span[@class=&quot;collapsed&quot;]/li[1]/a[@class=&quot;primary-link&quot;]</value>
      <webElementGuid>fd973c7c-1a0f-4f08-bb75-762893e22fd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Helpdesk/Page_greytHR/gt-ess-menu_View My Info_ng-star-inserted hydrated</value>
      <webElementGuid>814b5b77-5cf7-439e-9dab-5da943a4a624</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element_is_shadow_root</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>2bda73fe-0776-4b5a-a138-4b03753f36e7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Helpdesk')]</value>
      <webElementGuid>de4265b4-8d97-4618-bce6-fbb44106ee27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='']/parent::*</value>
      <webElementGuid>642966e6-c120-4922-9f84-d18cf6b87deb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'Helpdesk' or . = 'Helpdesk')]</value>
      <webElementGuid>844e0a00-c72e-4a28-bd3a-238b55d72543</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
