<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>gt-ess-menu_View My Info_ng-star-inserted hydrated</name>
   <tag></tag>
   <elementGuidId>230e2f8c-b703-4174-a661-3241e37fa22d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>gt-ess-menu.ng-star-inserted.hydrated</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//aside[@id='mainSidebar']/perfect-scrollbar/div/div/gt-ess-menu</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>gt-ess-menu</value>
      <webElementGuid>014b85ea-00de-4b49-be2e-de5e9d2e9b80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-star-inserted hydrated</value>
      <webElementGuid>972bd93a-a846-4d4f-840b-3532a984d7bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;hydrated&quot;]/body[@class=&quot;ng-tns-0-1&quot;]/app[1]/ng-component[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;desktop-view&quot;]/div[@class=&quot;side-and-content&quot;]/gt-sidebar[@class=&quot;ng-star-inserted&quot;]/aside[@id=&quot;mainSidebar&quot;]/perfect-scrollbar[1]/div[@class=&quot;ps&quot;]/div[@class=&quot;ps-content&quot;]/gt-ess-menu[@class=&quot;ng-star-inserted hydrated&quot;]</value>
      <webElementGuid>81c14178-4186-443a-8e6d-2f225654a5b8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//aside[@id='mainSidebar']/perfect-scrollbar/div/div/gt-ess-menu</value>
      <webElementGuid>7f52b286-665a-48e8-a8ae-6f7f3baf65c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//gt-ess-menu</value>
      <webElementGuid>35802cc7-91bf-4988-9637-c1a7574c7bc0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
