<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Reimbursement-ydrated-fe0</name>
   <tag></tag>
   <elementGuidId>e3270b0d-a16d-4723-a78a-59cf6df6e670</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>nav.w-full > ul > span.expanded > ul.secondary-nav > li:nth-of-type(6) > a.secondary-link</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Reimbursement')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>9dc45827-f9d3-4c86-b68a-ae489970cd27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>secondary-link</value>
      <webElementGuid>5e59f447-9f9d-4563-a280-e12f54c31308</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Reimbursement</value>
      <webElementGuid>3c44b486-5390-430a-b074-e593807d86e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/nav[@class=&quot;w-full&quot;]/ul[1]/span[@class=&quot;expanded&quot;]/ul[@class=&quot;secondary-nav&quot;]/li[6]/a[@class=&quot;secondary-link&quot;]</value>
      <webElementGuid>270c182a-15bc-44e5-8213-ee2995004ef1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Salary/Reimbursement/Page_greytHR/gt-ess-menu_View My Info_ng-star-inserted hydrated</value>
      <webElementGuid>143a70b5-516f-4e40-9a70-182c460d8eef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element_is_shadow_root</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>12080ffb-1c48-44d7-8ac5-e083455b01b5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Reimbursement')]</value>
      <webElementGuid>4ad388b2-a9d3-4b0f-be94-8f38a0db3e75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Reimbursement']/parent::*</value>
      <webElementGuid>321c2968-9ac2-485c-bf36-e40e88f024dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'Reimbursement' or . = 'Reimbursement')]</value>
      <webElementGuid>09a5439b-21b5-46d8-a399-14f5e8814be8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
