<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>gt-button_View My Info_mt-3x hydrated</name>
   <tag></tag>
   <elementGuidId>94599e0a-11d5-4d93-aadd-af14fbd04468</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>gt-button.mt-3x.hydrated</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//gt-button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>gt-button</value>
      <webElementGuid>48ee3a6d-5a6b-4059-8da3-1c993c2e991a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>shade</name>
      <type>Main</type>
      <value>primary</value>
      <webElementGuid>f16d58b6-e3b8-497c-a86c-d1e2e9fcb9d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mt-3x hydrated</value>
      <webElementGuid>2a8df1f4-6fd1-42ec-86b1-a039da69e59e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;hydrated&quot;]/body[@class=&quot;ng-tns-0-1&quot;]/app[1]/ng-component[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;desktop-view&quot;]/div[@class=&quot;side-and-content&quot;]/div[@class=&quot;container-fluid app-container px-0&quot;]/div[@class=&quot;router-container pb-15 container-fluid&quot;]/ng-component[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;emp-task-container&quot;]/task-board[1]/div[@class=&quot;gt-page-container&quot;]/div[@class=&quot;gt-page&quot;]/div[1]/div[@class=&quot;pt-16 flex flex-col justify-center items-center ng-star-inserted&quot;]/gt-button[@class=&quot;mt-3x hydrated&quot;]</value>
      <webElementGuid>5eb861ca-19e1-43bb-8e3b-44605030c470</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//gt-button</value>
      <webElementGuid>65e94ad9-9cfa-4245-b43d-e68cf2d281f3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
