<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>gt-ess-menu_View My Info_ng-star-inserted hydrated</name>
   <tag></tag>
   <elementGuidId>5a848e04-6205-4ac7-9727-4b1fd2192420</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>gt-ess-menu.ng-star-inserted.hydrated</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//aside[@id='mainSidebar']/perfect-scrollbar/div/div/gt-ess-menu</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>gt-ess-menu</value>
      <webElementGuid>82ee3743-d491-4348-8cf7-59bacd763916</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-star-inserted hydrated</value>
      <webElementGuid>1901cce7-fad7-4e63-93d5-f25c9e60c1a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;hydrated&quot;]/body[@class=&quot;ng-tns-0-1&quot;]/app[1]/ng-component[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;desktop-view&quot;]/div[@class=&quot;side-and-content&quot;]/gt-sidebar[@class=&quot;ng-star-inserted&quot;]/aside[@id=&quot;mainSidebar&quot;]/perfect-scrollbar[1]/div[@class=&quot;ps&quot;]/div[@class=&quot;ps-content&quot;]/gt-ess-menu[@class=&quot;ng-star-inserted hydrated&quot;]</value>
      <webElementGuid>064fe22a-a31f-4cd7-95d6-437b0b5d6adb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//aside[@id='mainSidebar']/perfect-scrollbar/div/div/gt-ess-menu</value>
      <webElementGuid>80e9e50e-2500-46e6-a53b-5177ae19eec5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//gt-ess-menu</value>
      <webElementGuid>46a1ffcc-7fa8-44b2-b2fc-ef1d048bf524</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
