<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_SignIn</name>
   <tag></tag>
   <elementGuidId>1f4bd07f-9e8c-4f91-9fda-3ec3c9e426a3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//gt-button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>gt-button.hydrated</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>gt-button</value>
      <webElementGuid>9160c68c-89d8-4b6f-970b-e95d501d2d0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>shade</name>
      <type>Main</type>
      <value>primary</value>
      <webElementGuid>308ffcf9-5c17-4b6c-9417-c3813456d811</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hydrated</value>
      <webElementGuid>8597fb53-c024-441e-a383-bed404bb386b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;hydrated&quot;]/body[@class=&quot;ng-tns-0-1&quot;]/app[1]/ng-component[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;desktop-view&quot;]/div[@class=&quot;side-and-content&quot;]/div[@class=&quot;container-fluid app-container px-0&quot;]/div[@class=&quot;router-container pb-15 container-fluid&quot;]/ghr-home[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;page page-home ng-star-inserted&quot;]/div[@class=&quot;home-dashboard&quot;]/gt-home-dashboard[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;gt-home-dashboard mb-1.5x&quot;]/div[@class=&quot;gt-widget-wrapper bg-white rounded-m border-secondary-200 hover:shadow-lg ng-star-inserted&quot;]/gt-component-loader[1]/gt-attendance-info[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;p-1.5x h-18x widget-border bg-white&quot;]/div[1]/div[@class=&quot;btn-container mt-3x flex flex-row-reverse justify-between ng-star-inserted&quot;]/gt-button[@class=&quot;hydrated&quot;]</value>
      <webElementGuid>1b931970-72ab-4eac-a867-5c2d6da1fd67</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//gt-button</value>
      <webElementGuid>0956c52f-2701-4982-a932-1cd70084cc21</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
