<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>gt-document-card_LettersPending0Closed0</name>
   <tag></tag>
   <elementGuidId>34a64370-8b5b-4721-8601-f838a33745c7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.pr-4.pb-4 > div.bg-white.rounded-sm.shadow-sm > gt-document-card.hydrated</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Request'])[1]/following::gt-document-card[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>gt-document-card</value>
      <webElementGuid>7fb057b8-6cdd-4f9e-92d4-b34b5c0d5357</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>icon-name</name>
      <type>Main</type>
      <value>letters</value>
      <webElementGuid>0324d3f3-a985-4623-828c-bf54df22d90e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>shade</name>
      <type>Main</type>
      <value>primary</value>
      <webElementGuid>9d997b5e-8c25-482b-96a2-4aea83a9560c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>btn-type</name>
      <type>Main</type>
      <value>link</value>
      <webElementGuid>546dc9bd-ceff-4573-be16-3a5a52bfee5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>btn-name</name>
      <type>Main</type>
      <value>View All</value>
      <webElementGuid>8f772f1c-6ff6-4ae3-bf58-8739b08f73a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hydrated</value>
      <webElementGuid>f99c5853-9ff0-45b5-a708-785812e9e7a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>LettersPending:0Closed:0</value>
      <webElementGuid>05bd95fc-2ff6-47ca-a3fe-e94763e83033</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;hydrated&quot;]/body[@class=&quot;ng-tns-0-1&quot;]/app[1]/ng-component[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;desktop-view&quot;]/div[@class=&quot;side-and-content&quot;]/div[@class=&quot;container-fluid app-container px-0&quot;]/div[@class=&quot;router-container pb-15 container-fluid&quot;]/ng-component[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;mt-1.5x flex flex-wrap ng-star-inserted&quot;]/div[@class=&quot;pr-4 pb-4&quot;]/div[@class=&quot;bg-white rounded-sm shadow-sm&quot;]/gt-document-card[@class=&quot;hydrated&quot;]</value>
      <webElementGuid>1c312ce9-7ae9-4964-ab6c-bc25c858a284</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Request'])[1]/following::gt-document-card[1]</value>
      <webElementGuid>dd4d6880-9cc1-412e-94a0-b48da3d1fa66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Forms'])[1]/following::gt-document-card[1]</value>
      <webElementGuid>1bffb57f-c3b9-4335-bf01-5f0b9d662c66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/gt-document-card</value>
      <webElementGuid>fee71194-3f1b-4949-8fa7-94d736c1cede</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//gt-document-card[(text() = 'LettersPending:0Closed:0' or . = 'LettersPending:0Closed:0')]</value>
      <webElementGuid>05ceb26b-a4f5-43b7-9ec2-8290bef0240b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
