<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>gt-ess-menu_View My Info_ng-star-inserted hydrated</name>
   <tag></tag>
   <elementGuidId>c8806fa3-fd33-46ed-87c4-762b4357d2d0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.transform.transition-all.w-full > gt-sidebar > #mainSidebar > perfect-scrollbar > div.ps > div.ps-content > gt-ess-menu.ng-star-inserted.hydrated</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//aside[@id='mainSidebar']/perfect-scrollbar/div/div/gt-ess-menu)[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>gt-ess-menu</value>
      <webElementGuid>607a9ad9-031d-4ce0-9f37-45e293b54e18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-star-inserted hydrated</value>
      <webElementGuid>ecbf0624-e77b-431d-98e9-7103d841c528</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;hydrated&quot;]/body[@class=&quot;ng-tns-0-1&quot;]/app[1]/ng-component[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;mobile-view&quot;]/div[@class=&quot;side-and-content&quot;]/div[@class=&quot;fixed z-10 inset-0 block ng-star-inserted&quot;]/div[@class=&quot;flex h-screen&quot;]/div[@class=&quot;transform transition-all w-full&quot;]/gt-sidebar[1]/aside[@id=&quot;mainSidebar&quot;]/perfect-scrollbar[1]/div[@class=&quot;ps&quot;]/div[@class=&quot;ps-content&quot;]/gt-ess-menu[@class=&quot;ng-star-inserted hydrated&quot;]</value>
      <webElementGuid>628d4031-a207-45a7-a0b0-d1daf3c1abea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//aside[@id='mainSidebar']/perfect-scrollbar/div/div/gt-ess-menu)[2]</value>
      <webElementGuid>a485971e-0664-413a-8912-c23dc0811c62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/gt-sidebar/aside/perfect-scrollbar/div/div/gt-ess-menu</value>
      <webElementGuid>96aa986a-30dd-4524-a693-a434fc3c86f7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
