<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Home_image-hamburger hamburger-containe_aa29aa</name>
   <tag></tag>
   <elementGuidId>8fca1e6c-3f44-41fc-9fa7-73b60275eb46</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.image-hamburger.hamburger-container.ng-star-inserted</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//nav/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0f26dc6b-f2cb-4f88-af9a-53731f9aa8d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>image-hamburger hamburger-container ng-star-inserted</value>
      <webElementGuid>0948447a-ae70-4b5d-8e03-08a4685801f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;hydrated&quot;]/body[@class=&quot;ng-tns-0-1&quot;]/app[1]/ng-component[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;mobile-view&quot;]/gt-topbar[@class=&quot;ng-star-inserted&quot;]/nav[@class=&quot;navbar bg-secondary-50 navbar-fixed-top ng-star-inserted&quot;]/div[@class=&quot;page-title relative&quot;]/div[@class=&quot;image-hamburger hamburger-container ng-star-inserted&quot;]</value>
      <webElementGuid>df60ad3e-4dda-4bb0-9ce8-fa2a46b27b65</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/div/div</value>
      <webElementGuid>2c58c963-8fad-4e1d-b269-52c1afb31d27</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
