<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Home_image-gt-icon-notification h-2x w-2x</name>
   <tag></tag>
   <elementGuidId>6b3b9ce8-2dfd-4420-90f2-e523ff4d5f63</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.image-gt-icon-notification.h-2x.w-2x</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5174d382-50f9-4645-8e45-14f41e4bf52f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>image-gt-icon-notification h-2x w-2x</value>
      <webElementGuid>1a096cd1-4c76-405a-b70e-ce190bd9bdb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;hydrated&quot;]/body[@class=&quot;ng-tns-0-1&quot;]/app[1]/ng-component[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;mobile-view&quot;]/gt-topbar[@class=&quot;ng-star-inserted&quot;]/nav[@class=&quot;navbar bg-secondary-50 navbar-fixed-top ng-star-inserted&quot;]/div[@class=&quot;menu&quot;]/gt-notification[1]/div[@class=&quot;icon-container&quot;]/a[@class=&quot;icon-link&quot;]/div[@class=&quot;image-gt-icon-notification h-2x w-2x&quot;]</value>
      <webElementGuid>cdaeb08e-3fff-4e0c-a194-9df097dbff95</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div</value>
      <webElementGuid>53c15d39-afc3-4ef3-a950-94ef68b94dca</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
