<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Closed_searchKey</name>
   <tag></tag>
   <elementGuidId>eb694413-5f2d-4b07-89df-6f1569c8eec2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;searchKey&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='searchKey']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4577ce04-de13-4824-85a7-da42db9a9b0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>cec867fe-f99a-44fb-b3e7-cf8cbbc28319</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search Employee</value>
      <webElementGuid>4c709d6d-625b-41a3-bfa1-bfdc366d37c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>searchKey</value>
      <webElementGuid>7ccf43a8-3f7c-41c3-8513-f23a62851801</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>typeaheadoptionfield</name>
      <type>Main</type>
      <value>name</value>
      <webElementGuid>9022934c-ce8e-4c30-b4e8-8defa9e945f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>typeaheadwaitms</name>
      <type>Main</type>
      <value>300</value>
      <webElementGuid>56a23899-3b44-48da-ae54-d58e74459521</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control text-overflow ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>5c090249-0b0a-4477-a9ee-8f4dac9a5a0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>9f673a3a-27ce-431a-b764-c0f3ce6e0561</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>list</value>
      <webElementGuid>113e85e5-d601-4c4e-8ac2-dde5764d275f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;hydrated&quot;]/body[@class=&quot;ng-tns-0-1&quot;]/app[1]/ng-component[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;mobile-view&quot;]/div[@class=&quot;side-and-content&quot;]/div[@class=&quot;container-fluid app-container px-0&quot;]/div[@class=&quot;router-container pb-15 container-fluid&quot;]/workflow[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;wf-review&quot;]/div[@class=&quot;row wf-review-content&quot;]/div[@class=&quot;col-md-9 col-lg-9 py-2x ml-3x&quot;]/attendance-regularization-review-listing[@class=&quot;ng-star-inserted&quot;]/gt-workflow-list[1]/div[@class=&quot;workflow-list-view&quot;]/div[@class=&quot;workflow-list-control ng-star-inserted&quot;]/div[@class=&quot;workflow-list-control-filters&quot;]/div[@class=&quot;orginasation-employees ng-star-inserted&quot;]/div[@class=&quot;organisation-employees-search&quot;]/div[@class=&quot;search-bar-container&quot;]/div[@class=&quot;employee-search&quot;]/div[@class=&quot;input-with-icon&quot;]/input[@class=&quot;form-control text-overflow ng-untouched ng-pristine ng-valid&quot;]</value>
      <webElementGuid>ba0e4137-6e58-4c94-91a4-2d8fb9c45fd8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='searchKey']</value>
      <webElementGuid>1a5070e7-97a7-441c-95e0-5f48068df37a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/input</value>
      <webElementGuid>062baa3a-86e4-4272-90c0-9f634743fa02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Search Employee' and @name = 'searchKey']</value>
      <webElementGuid>7581c05b-a8e4-4052-bd18-527e253a1551</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
