<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Payslip_inline-block image-gt-icon-wid_46ee29</name>
   <tag></tag>
   <elementGuidId>263027d8-35b9-40dd-ab88-2e0cc47a9d8f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//gt-payslip-widget/div/header/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>eb2d9a54-e647-40ec-a0aa-9d75e459991d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inline-block image-gt-icon-widget h-2.5x w-2.5x</value>
      <webElementGuid>0ec2dc28-831f-4fed-adfe-58e4f4aa20c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;hydrated&quot;]/body[@class=&quot;ng-tns-0-1&quot;]/app[1]/ng-component[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;mobile-view&quot;]/div[@class=&quot;side-and-content&quot;]/div[@class=&quot;container-fluid app-container px-0&quot;]/div[@class=&quot;router-container pb-15 container-fluid&quot;]/ghr-home[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;page page-home ng-star-inserted&quot;]/div[@class=&quot;home-dashboard&quot;]/gt-home-dashboard[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;gt-home-dashboard mb-1.5x&quot;]/div[@class=&quot;gt-widget-wrapper bg-white rounded-m border-secondary-200 hover:shadow-lg ng-star-inserted&quot;]/gt-component-loader[1]/gt-payslip-widget[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;p-1.5x widget-height ng-star-inserted&quot;]/header[@class=&quot;cursor-pointer outline-none flex items-center justify-between mb-1.5x&quot;]/span[@class=&quot;inline-block image-gt-icon-widget h-2.5x w-2.5x&quot;]</value>
      <webElementGuid>2a8abba6-f6fb-4df8-b323-066c87438036</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//gt-payslip-widget/div/header/span</value>
      <webElementGuid>05b52641-1072-4c8d-bac0-40b4bce32ae9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
