<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Leave-ydrated-f83</name>
   <tag></tag>
   <elementGuidId>4e8e9215-ef01-4b43-a5bd-37d80a3538a1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>nav.w-full > ul > span.collapsed > li > a.primary-link</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Leave')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e1438b22-0cf6-4f61-bd47-d87d2290592a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>primary-link</value>
      <webElementGuid>2bd5df73-a80a-4a6d-abb1-4f258de381ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Leave</value>
      <webElementGuid>1952b928-efae-4227-aa83-bcd1e308cd7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/nav[@class=&quot;w-full&quot;]/ul[1]/span[@class=&quot;collapsed&quot;]/li[1]/a[@class=&quot;primary-link&quot;]</value>
      <webElementGuid>dd7b65ea-f6d5-4bd8-b237-0d0bb6789a78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Leave/LeaveApply/gt-ess-menu_View My Info_ng-star-inserted hydrated</value>
      <webElementGuid>31d9ec44-bba8-4396-a7c4-d113add6fa80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element_is_shadow_root</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d4e38a4f-fd4f-47cd-9314-0a7970733761</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Leave')]</value>
      <webElementGuid>f040b273-527a-4712-a7d6-61baceded4d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='']/parent::*</value>
      <webElementGuid>f0a5b03c-0d03-45b4-968a-48ff84790123</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'Leave' or . = 'Leave')]</value>
      <webElementGuid>f720c9c0-566a-4cad-899f-d0359b5bdd44</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
