<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Contact details_contactDetails</name>
   <tag></tag>
   <elementGuidId>4e1916cb-63b9-4758-b30f-95fc9511b8cd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#contactDetailsField</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='contactDetailsField']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5c0413a4-d092-41ef-90c8-d7dc9f951051</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>32bd7762-18d5-4943-b97f-71a7795fb960</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>contactDetailsField</value>
      <webElementGuid>a2d5f1b3-d4c1-4b66-aae4-31784638e878</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>contactDetails</value>
      <webElementGuid>594b8df1-c6f8-4899-bd94-3dc4885ea0d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>contact-number form-control ng-untouched ng-valid ng-dirty</value>
      <webElementGuid>1f1f3ee3-35ab-4be5-9d66-98fb95526c0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>2000</value>
      <webElementGuid>7cb61081-75d4-4dbf-bfd3-f5aa28e342fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;contactDetailsField&quot;)</value>
      <webElementGuid>6a9e83d3-aedb-42fb-b2ea-942e26f9ea78</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='contactDetailsField']</value>
      <webElementGuid>3c927996-c6e8-4e51-b6b5-bb7d1a242424</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>b43b15e0-25a8-4e14-a99b-557ef88ee1af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'tel' and @id = 'contactDetailsField' and @name = 'contactDetails']</value>
      <webElementGuid>2fae39d2-2ef0-439f-8e4f-07874756dc8c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
