<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Reason_reason</name>
   <tag></tag>
   <elementGuidId>5e3bb1fd-0cc7-4b38-bb2b-451735cbe5ed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#reasonField</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='reasonField']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>bd43749f-8277-4c30-8884-7d41b4ceccf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter a reason</value>
      <webElementGuid>a164bc04-f9f1-4968-b263-f03ee864beab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>reason</value>
      <webElementGuid>1e2c1b38-2831-42c8-942b-ca0c0b1fa4ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>reasonField</value>
      <webElementGuid>bb4f6ed8-37ed-402e-97c4-4632e3776940</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>leave-reason form-control ng-untouched ng-valid ng-dirty</value>
      <webElementGuid>5775d59b-43fc-4a19-8f8f-624642fcf02a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>2000</value>
      <webElementGuid>55010d03-d301-4c16-8661-4fe71be08012</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;reasonField&quot;)</value>
      <webElementGuid>40404401-1a16-42cf-ac1a-f29b91f079c0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='reasonField']</value>
      <webElementGuid>781d4da6-9398-41e9-a6c6-b09a71cfab01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reason'])[1]/following::textarea[1]</value>
      <webElementGuid>4081c180-0f4f-4828-8a18-9bebaeeac410</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact details'])[1]/following::textarea[1]</value>
      <webElementGuid>e8e9d631-8d73-4c31-8a53-586095bc3079</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Attach File'])[1]/preceding::textarea[1]</value>
      <webElementGuid>5cd3c452-b3e6-4bc1-b646-1cce1fcfaec7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Document Preview'])[1]/preceding::textarea[1]</value>
      <webElementGuid>06702163-b9da-4878-9130-2864f8628826</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>b8cac798-0a2c-41ea-934a-e812d39e0e22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@placeholder = 'Enter a reason' and @name = 'reason' and @id = 'reasonField']</value>
      <webElementGuid>56be5e5c-563e-403a-85de-49fcb54ffbb4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
