<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Upcoming Holidays_inline-block image-g_47b19d</name>
   <tag></tag>
   <elementGuidId>1854fd60-7c80-406e-95e1-4e86d9c039b5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ng-component/div/header/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>85eb8e63-db2e-47bc-ae5b-437ca9e27656</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inline-block image-gt-icon-widget h-2.5x w-2.5x ng-star-inserted</value>
      <webElementGuid>3a5af291-8fba-4fcc-bb96-4b40b1b04c5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;hydrated&quot;]/body[@class=&quot;ng-tns-0-1&quot;]/app[1]/ng-component[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;desktop-view&quot;]/div[@class=&quot;side-and-content&quot;]/div[@class=&quot;container-fluid app-container px-0&quot;]/div[@class=&quot;router-container pb-15 container-fluid&quot;]/ghr-home[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;page page-home ng-star-inserted&quot;]/div[@class=&quot;home-dashboard&quot;]/gt-home-dashboard[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;gt-home-dashboard mb-1.5x&quot;]/div[@class=&quot;gt-widget-wrapper bg-white rounded-m border-secondary-200 hover:shadow-lg ng-star-inserted&quot;]/gt-component-loader[1]/ng-component[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;p-1.5x&quot;]/header[@class=&quot;cursor-pointer outline-none flex items-center justify-between&quot;]/span[@class=&quot;inline-block image-gt-icon-widget h-2.5x w-2.5x ng-star-inserted&quot;]</value>
      <webElementGuid>e8cfc012-b804-4632-a79c-eb6f7f202bcf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ng-component/div/header/span</value>
      <webElementGuid>53fe32ea-57ce-4a52-bc2b-6cda1b1703c9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
