<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Hide</name>
   <tag></tag>
   <elementGuidId>619fe47a-f8b4-4ece-8451-574f0d97f92f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.underlined-link.text-4.text-bold</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Hide')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0da0f348-9c4a-4535-a60b-12b6c29ef147</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>underlined-link text-4 text-bold</value>
      <webElementGuid>712f8c8f-a3db-4c89-8fb3-5632ee1b0902</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Hide </value>
      <webElementGuid>947cb2ac-0950-4656-9161-02e2f89fb9fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;hydrated&quot;]/body[@class=&quot;ng-tns-0-1&quot;]/app[1]/ng-component[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;desktop-view&quot;]/div[@class=&quot;side-and-content&quot;]/div[@class=&quot;container-fluid app-container px-0&quot;]/div[@class=&quot;router-container pb-15 container-fluid&quot;]/ng-component[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12 col-lg-12&quot;]/ng-component[@class=&quot;ng-star-inserted&quot;]/payslip-data-display[1]/div[@class=&quot;payslip-data-container ng-star-inserted&quot;]/div[@class=&quot;row ng-star-inserted&quot;]/div[@class=&quot;col-md-4 col-lg-4&quot;]/gt-user-info-well[@class=&quot;ng-star-inserted&quot;]/section[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;container-fluid user-info-well gt-info-well gt-well-no-border ng-star-inserted&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12 hide-info-btn-container&quot;]/a[@class=&quot;underlined-link text-4 text-bold&quot;]</value>
      <webElementGuid>d4f4fbdf-619b-46d4-b28c-777a798f9171</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Hide')]</value>
      <webElementGuid>f2992889-e739-4c07-8ab1-942a32ffa2e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Employee details'])[1]/following::a[1]</value>
      <webElementGuid>5acd26fb-1551-405a-af0f-8a66bd12b0cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total'])[1]/following::a[1]</value>
      <webElementGuid>e00fef82-f84a-4c95-97f6-57434ac05196</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Name'])[1]/preceding::a[1]</value>
      <webElementGuid>0d42e831-bb9a-4f61-b8e7-a321c3e68163</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Yogeshwaran S'])[1]/preceding::a[1]</value>
      <webElementGuid>75cb3b7c-4982-40ce-b976-e6a11e7c264e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Hide']/parent::*</value>
      <webElementGuid>8a16c125-2c1e-432c-993d-0d1c76b21d31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/a</value>
      <webElementGuid>05fbead3-3541-47bc-a229-fe4dc5245c96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = ' Hide ' or . = ' Hide ')]</value>
      <webElementGuid>cc4764df-8b24-4f64-8823-1d77f58f2e22</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
