<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Salary-ydrated-4b6</name>
   <tag></tag>
   <elementGuidId>25d1d24e-287e-4571-b553-11a3b77c528b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>nav.w-full > ul > span.collapsed > li > a.primary-link</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Salary')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>480607fa-a07d-448e-a444-250409f4c6f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>primary-link</value>
      <webElementGuid>755cbda5-22dc-4c60-b3f8-7bda5f95bf0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Salary</value>
      <webElementGuid>ac3bbb38-d7d8-4735-8601-1b3b6c8b1962</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/nav[@class=&quot;w-full&quot;]/ul[1]/span[@class=&quot;collapsed&quot;]/li[1]/a[@class=&quot;primary-link&quot;]</value>
      <webElementGuid>fe4a634a-0aac-42e7-9083-7e17991e8209</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Salary/Payslips/Page_greytHR/gt-ess-menu_View My Info_ng-star-inserted hydrated</value>
      <webElementGuid>b1b84352-7803-499a-9fb0-e13fcf31bbf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element_is_shadow_root</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>47209c1d-0ad7-4a93-b22f-18a248e53758</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Salary')]</value>
      <webElementGuid>72c217a1-9679-4cad-a7a8-5f44d860d810</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='']/parent::*</value>
      <webElementGuid>76f39e1e-ced8-4c54-8d86-c739ceeabb6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'Salary' or . = 'Salary')]</value>
      <webElementGuid>6b9badc9-bb09-4e5b-a97f-f4c8abceffd4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
