<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Salary-ydrated-4b6</name>
   <tag></tag>
   <elementGuidId>d77e22ec-35a4-4ef7-aa6d-ef21fe965dda</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>nav.w-full > ul > span.collapsed > li > a.primary-link</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Salary')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1501b890-83dc-43d6-bc74-850a8fd491bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>primary-link</value>
      <webElementGuid>ba9c6b24-a2db-42d7-9bfa-9b0af56695ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Salary</value>
      <webElementGuid>99c67a0d-9269-4860-932c-9245b35f415c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/nav[@class=&quot;w-full&quot;]/ul[1]/span[@class=&quot;collapsed&quot;]/li[1]/a[@class=&quot;primary-link&quot;]</value>
      <webElementGuid>a9cf3e33-2c94-47b1-8e05-1db9af90f342</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Salary/Proof Of Investment/Page_greytHR/gt-ess-menu_View My Info_ng-star-inserted hydrated</value>
      <webElementGuid>aee4274c-207b-4a9c-a97f-1fdfedbe4530</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element_is_shadow_root</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e84db1b7-1444-4652-8038-fa520d825c79</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Salary')]</value>
      <webElementGuid>e9161c8e-4ee5-415a-bf2d-cc9b5930b884</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='']/parent::*</value>
      <webElementGuid>2bac920f-09db-4002-a33e-076ac0f389d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'Salary' or . = 'Salary')]</value>
      <webElementGuid>01f4d8b9-a7d1-46b5-9495-bd5f6bf8e94b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
