<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>gt-ess-menu_View My Info_ng-star-inserted hydrated</name>
   <tag></tag>
   <elementGuidId>d35940d6-4ebd-493d-82a1-3722b7b0c9e6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>gt-ess-menu.ng-star-inserted.hydrated</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//aside[@id='mainSidebar']/perfect-scrollbar/div/div/gt-ess-menu</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>gt-ess-menu</value>
      <webElementGuid>7408f496-2cf0-4526-841b-cf9b5e775e08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-star-inserted hydrated</value>
      <webElementGuid>513c7cc7-36f8-4772-adac-7fde23b55a1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;hydrated&quot;]/body[@class=&quot;ng-tns-0-1&quot;]/app[1]/ng-component[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;desktop-view&quot;]/div[@class=&quot;side-and-content&quot;]/gt-sidebar[@class=&quot;ng-star-inserted&quot;]/aside[@id=&quot;mainSidebar&quot;]/perfect-scrollbar[1]/div[@class=&quot;ps&quot;]/div[@class=&quot;ps-content&quot;]/gt-ess-menu[@class=&quot;ng-star-inserted hydrated&quot;]</value>
      <webElementGuid>0327d167-462a-425b-9cb5-8d3ffc2d9801</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//aside[@id='mainSidebar']/perfect-scrollbar/div/div/gt-ess-menu</value>
      <webElementGuid>2bd5f13e-2227-4f46-be4c-4278b853648a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//gt-ess-menu</value>
      <webElementGuid>ec564bb2-3596-4b91-bb4d-92169445ef96</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
